services:
  - type: web
    name: itam-air-engine-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
